name: FactionsPro
author: [Tethered_ & Day]
description: A Plugin For Easily Managing Guilds
version: 1.8.0
main: FactionsPro\FactionMain
api:
- 1.14.0
- 2.0.0
commands:
  fac:
    description: use /fac help for all parameters
    permission: f.command
  f:
    description: use /guilds help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all guilds commands"
